### ISSUE TITLE
The download of the signed file doesn't work when S3 is enabled

### ISSUE THREAD

**Issue by myugan** [documenso/documenso#768] opened 2023-12-18 10:47 UTC
### Issue Description

I'm using version v1.2.3 and it appears that using an S3 bucket as file storage is causing some issues. I've noticed that even after the signing is completed, I'm unable to download the file despite having full S3 access to the specified bucket through IAM configuration.

### Steps to Reproduce

Just by following the steps on how to upload a document and add a signer, after the signer gives a signature, we receive a notification to download the file. Alternatively, the page will display a download button after the signature is completed.

### Expected Behavior

Download button should be working fine

### Current Behavior

Not able to download signed document.

### Screenshots (optional)

<img width="2056" alt="image" src="https://github.com/documenso/documenso/assets/20453528/331219b4-b260-4211-b347-2ea0afd6556a">

<img width="425" alt="image" src="https://github.com/documenso/documenso/assets/20453528/30c810bb-e266-40f7-a4b4-227ef8f3153e">

### Browser [e.g., Chrome, Firefox]

Firefox

### Version [e.g., 2.0.1]

v1.2.3

### Please check the boxes that apply to this issue report.

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by catalinpit** [comment] 2023-12-19 09:13
Thanks for signalling this issue @myugan!

**Comment by VishalMCF** [comment] 2023-12-20 12:26
Hello Do I need to setup any S3 bucket using localstack or the docker cotainers -> inbucket/minio will be sufficient to debug this issue?

**Comment by catalinpit** [comment] 2023-12-20 12:32
> Hello Do I need to setup any S3 bucket using localstack or the docker containers -> inbucket/minio will be sufficient to debug this issue? I feel it should be sufficient as what mentioned in the docker-compose file (about minio) is what matches with the .env.example file

Minio should be fine. That's what I use as well.

**Comment by myugan** [comment] 2023-12-20 13:13
I prefer using an S3 bucket because it doesn't require maintenance and its storage capacity isn't dependent on the operating system. I've noticed the new addition of MinIO for storage, but personally, I would rather not use it

**Comment by VishalMCF** [comment] 2023-12-20 13:15
@myugan @catalinpit I cloned the project yesterday and I did all the steps. In my case I am able to download the file after successful siging in. Think it is a version issue only.

**Comment by Aj7Ay** [comment] 2023-12-20 13:33
@VishalMCF Are you currently able to download files successfully? Additionally, we are using version 1.3.0 and encountering an error.

**Comment by VishalMCF** [comment] 2023-12-20 13:43
Hello @Aj7Ay I will tell you what I did when I ran locally:-
1. NEXT_PUBLIC_UPLOAD_TRANSPORT="s3"
Logged in using OAuth and assigned myself a file to sign.
After signing the file I got this page:-
![image](https://github.com/documenso/documenso/assets/70262922/bf9243ec-cd02-4644-a34f-efb6f3349de9)

Then when i click on download button it shows file downloaded.
<img width="1351" alt="Screenshot 2023-12-20 at 7 11 42 PM" src="https://github.com/documenso/documenso/assets/70262922/11b2b225-f966-4067-86e5-646c25bc6e98">

**Comment by catalinpit** [comment] 2024-01-08 13:57
> @myugan @catalinpit I cloned the project yesterday and I did all the steps. In my case I am able to download the file after successful siging in. Think it is a version issue only. Do we have to update that version ? If yes then I am not sure how I can edit that version source code.

Couldn't reproduce either. Will close this for now, and if there will be more reports, we'll investigate it.

@Aj7Ay if you can't manage to make it work, ping me on Discord and we'll have a look together. Thanks!

**Comment by catalinpit** [comment] 2024-01-09 09:19
Ok, I tried using AWS directly and still can't reproduce the issue. Can anyone reproduce it or did anyone reproduce it recently?

**Closed** 2024-01-12 08:58 UTC
Labels: bug, Reliability, public, apps: web, needs triage
