### ISSUE TITLE
[Bug] - Issue with Responsiveness of Signup Now modal

### ISSUE THREAD

**Issue by adithyaakrishna** [documenso/documenso#509] opened 2023-10-03 14:13 UTC
**Description:**

Similar to #507 the _**Signup Now**_ modal at https://documenso.com/pricing seems to be messed up. Please refer to the screenshot below for more reference.

![IMG_9073](https://github.com/documenso/documenso/assets/23498248/1f2998a2-7ca2-4410-ae54-a0c96765a64a)

The expected outcome would be to center the modal with sufficient margins around it keeping in mind the responsiveness of it.

**Comment by adityadeshlahre** [comment] 2023-10-03 18:11
i would like to take this :smile: !

**Comment by adithyaakrishna** [comment] 2023-10-03 19:07
@adityadeshlahre Awesome! Please feel free to take this up and send a PR towards it :)

**Comment by dguyen** [comment] 2023-10-05 08:56
Sorry I should have looked more in-depth before work was done, but this is basically a duplicate of #507

Going to close this

**Closed by dguyen** 2023-10-05 08:56 UTC
Labels: bug, public
