### ISSUE TITLE
Email verification is never sent

### ISSUE THREAD

**Issue by parasiteoflife** [documenso/documenso#1363] opened 2024-09-23 08:37 UTC
### Issue Description

Just set up in docker but I can't confirm the account, the email is never sent, there are no errors on the logs, it just says

```
Submitting job to endpoint: http://localhost:3000/api/jobs/send.signup.confirmation.email/xxxxxxxxxxxxxxxxxxxxx
Eligible jobs: [ 'Send Confirmation Email' ]
```

I have tried it all, disabling TLS, changing email server port, nothing works. Mailserver shows no sign of login (to the sender account). I've found similar issues but most of them are about errors, I get no error.

### Steps to Reproduce

Just register

### Expected Behavior

Email to be sent

### Current Behavior

I mean, I already said no email is sent

### Operating System [e.g., Windows 10]

Debian 12

### Browser [e.g., Chrome, Firefox]

Doesn't matter

### Version [e.g., 2.0.1]

I don't know, can't signin but I guess current latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ephraimduncan** [comment] 2024-09-23 09:16
Closing this as a duplicate of this #1307 

Check if this solves your issue. https://github.com/documenso/documenso/issues/1307#issuecomment-2365339402

If It doesn't, can you provide further information on the same issue? Thank you

**Closed by ephraimduncan** 2024-09-23 09:16 UTC
Labels: duplicate, status: triage
