### ISSUE TITLE
[Bug] - Prevent Horizontal Scrolling of the website on mobile views

### ISSUE THREAD

**Issue by adithyaakrishna** [documenso/documenso#510] opened 2023-10-03 14:20 UTC
**Description:**

The responsiveness of the site at https://documenso.com/ for mobile views seems to be messed up and leads to horizontal scrolling on various mobile devices.

Please refer to the video attached below for more reference :)

https://github.com/documenso/documenso/assets/23498248/2e1b102c-b205-4756-b36e-d822ca3aff27

The expected outcome would be to prevent horizontal scrolling while keeping all the contents to the center of the screen

**Comment by thara003** [comment] 2023-10-03 18:20
I would like to work on this issue 😃

**Comment by adithyaakrishna** [comment] 2023-10-03 19:07
@thara003 Awesome! Please feel free to take this up and send a PR towards it :)

**Comment by dguyen** [comment] 2023-10-06 01:31
@adithyaakrishna could you please provide us with your screen width size?

In addition, does this only occur on brave browser?

**Comment by thara003** [comment] 2023-10-06 07:39
@dguyen I tried opening the website in both brave and google, but couldn't find any horizontal scroll issue unless it's zoomed. 
Though some components looked overflowing. I have fixed this issue in my PR.

example screenshot:
![WhatsApp Image 2023-10-06 at 1 07 18 PM](https://github.com/documenso/documenso/assets/79561774/1a1afd4c-b9d9-4d07-94a5-030ec675f421)

**Comment by dguyen** [comment] 2023-10-09 08:34
Going to close this issue as it's pretty much a duplicate of #508.

@thara003 you can continue to work on your changes in your PR as part of a separate enhancement to the marketing page.

**Closed by dguyen** 2023-10-09 08:34 UTC
Labels: bug, public

**Comment by thara003** [comment] 2023-10-09 08:46
of course, will do that
