### ISSUE TITLE
🐛 bug: Unable to delete selected signatures block on touchscreens

### ISSUE THREAD

**Issue by ashrafchowdury** [documenso/documenso#798] opened 2024-01-01 10:23 UTC
### Issue Description

**Unable to delete selected signatures, email blocks, and other blocks using touch screens.** This issue is primarily observed on touchscreen devices, such as mobile phones.

### Steps to Reproduce

1. Access the document/interface where blocks are present.
2. Check what's wrong with the smaller screens.
3. Then fix the issue.

### Expected Behavior

Blocks should be deleted successfully when the delete action is performed, regardless of device type.

### Current Behavior

Blocks remain in place and cannot be deleted using touchscreen interactions.

### Screenshots (optional)

https://github.com/documenso/documenso/assets/87828904/64f3ca91-09aa-4354-8900-0d798a9d98dd

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome, Edge

### Version [e.g., 2.0.1]

Latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by imadipal** [comment] 2024-01-02 03:06
@ashrafchowdury Let me find the root cause of this, will fix this soon.

**Comment by ashrafchowdury** [comment] 2024-01-02 04:07
> @ashrafchowdury Let me find the root cause of this, will fix this soon.

Hay @imadipal, can I work on this issue?

**Comment by Nisarg-Sha** [comment] 2024-01-02 11:31
Can you please assign this to me ?

**Comment by Mythie** [comment] 2024-01-04 04:51
Hey all, Ashraf has indicated that they would like to work on it if approved so I'll let him take care of it!

Approved to be worked on 😄

**Comment by ashrafchowdury** [comment] 2024-01-06 04:08
Hay, I'm getting this eslint error message while trying to commit my code.

![image](https://github.com/documenso/documenso/assets/87828904/691167e1-db8a-4bcf-a463-18590753ae86)

My code changes

![image](https://github.com/documenso/documenso/assets/87828904/e3f9b642-091a-46bc-beb8-d36de1228638)

I've just added this one line of code.

**Comment by imadipal** [comment] 2024-01-06 05:36
@ashrafchowdury, Formatted in the IDE that you are using?

**Comment by ashrafchowdury** [comment] 2024-01-06 06:30
@imadipal,  I'm using `Prittier` to format the code.

![image](https://github.com/documenso/documenso/assets/87828904/a56c2586-5beb-465d-9e9b-da63d4bcb2b4)


here is my IDE default format
![image](https://github.com/documenso/documenso/assets/87828904/0f9ae875-ff2c-4557-baf0-33e1c2e28988)

**Closed** 2024-01-15 08:33 UTC
Labels: bug, assigned
